name: CI Pipeline with Versioned Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: product_catalog_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/product_catalog_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Get project version
        id: get_version
        run: echo "VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - name: Build and test project
        run: ./gradlew build

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: urfu-cakeshop
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/urfu-cakeshop/cake-shop-product-catalog-service
          docker build -t $IMAGE:latest -t $IMAGE:${GITHUB_SHA} -t $IMAGE:${VERSION} .

      - name: Security scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/urfu-cakeshop/cake-shop-product-catalog-service:latest

      - name: Push Docker image
        run: |
          IMAGE=ghcr.io/urfu-cakeshop/cake-shop-product-catalog-service
          docker push $IMAGE:latest
          docker push $IMAGE:${GITHUB_SHA}
          docker push $IMAGE:${VERSION}